# Site settings
title: megejor
email: meghanelizabethj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  the unblog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://megejor.com" # the base hostname & protocol for your site
#url: "http://localhost:4000"
twitter_username:
github_username:  meghanelizabeth

# Build settings
markdown: kramdown
permalink: pretty
